name: groundingDINO
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - numpy
  - matplotlib
  - pandas
  - pip:
      - torch==1.12.1+cu113
      - torchvision==0.13.1+cu113
      - torchaudio==0.12.1
      - opencv-python
      - supervision==0.6.0
      - transformers
      - timm
